### ISSUE TITLE
Major UX pain points

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1117]
I'm opening this issue to track what I consider major UX pain points with Qubes at present. My criteria for these is:
- Is a show stopping bug / failure that a user can't recover from
- The task complex and have a high possibility of mistakes to perform
- Requires using the command line
- Is unsolvable for all but the most technically savvy users

**BIOS / Hardware Related**
- [ ] Configuring BIOS settings to allow installation
- [x] Creating a USB AppVM (especially difficult on systems with USB 3) 
- [ ] Knowing which device drivers are which device is overly technical (USB, SD Card Bluetooth)
- [ ] USB VM does not recover from "not enough memory" #1449
- [ ] Add support for mounting exFAT partitions by default #1054

**GUI Related**
- [x] User needs to have a GUI way to update dom0 #1739 
- [ ] Better GUI support to install & update Templates
- [ ] Improve usability of resizing VM disk size #1053
- [ ] Make resizing of VM disk root.img doable from GUI #1441
- [ ] How to safely install & run multiple types of apps not in OS packages
- [ ] GUI support like UNetbootin to making bootable USB sticks of Qubes #1415
- [ ] Improve displayed apps and default VMs #1139
- [x] Improve GUI tools and errors for copying / moving files between VMs #1240 
- [ ] Special characters in window titles do not render #1059
- [x] have AdminVM manage inter-vm file copying #910 #1443

**Security**
- [ ] Qubes MIME handlers / opening links #441 #1080

**Stability**
- [ ] WiFi networking NetVM crashes #1470
- [ ] Soft windows not always fully rendered #1451

**Might be unsolvable due to the security design of Qubes**
- [ ] Cursor state (pointer, arrow, etc...) unable to change #1551
- [ ] Cursor unable to read / detect content in a window (e.g. color picker in Gimp or Inkscape)

_Other users, feel free to add comments on anything they encounter that feels like a significantly large and discreet UX pain point._

**Comment by unman** [comment]
What's the issue with creating a USB appVM? It doesn't seem to satisfy any of your criteria.

**Comment by bnvk** [comment]
@unman the only way I could get an AppVM to mount any USB devices was to go into my BIOS and disable USB 3.0. I discovered this from a thread in the Users Group.

**Comment by mfc** [comment]
I would add:
- [ ] user needs to have a GUI way to update dom0, install templates

**Comment by bnvk** [comment]
Adding this pain point, as it's something I struggle with a bit

- [ ] How to safely install & run multiple types of apps not in OS packages

An example of this is say [the Electrum Bitcoin wallet](https://electrum.org/#download). Where does one do each part of this installation process. Does a user download the tar file, verify the signature, untar it, then copy to TemplateVM? And then run the install

I realize, this type of use case only pertains to CLI users and not our ultimate target user who relies on the GUI, but would be nice to have more docs that explain better / how and where to do processes like this!

**Comment by axon-qubes** [comment]
> How to safely install & run multiple types of apps not in OS packages

Indeed, but the answer seems to be software-specific in many cases, so I wonder about our ability to provide guidance which is both sufficiently general to encompass many different programs while being specific enough to be useful.

Perhaps the closest thing to a generally-applicable procedure is simply to use a StandaloneVM in any case where the program requires persistent write access to any part of the root filesystem. At any rate, this has been the de facto solution for me in many cases.

**Comment by bnvk** [comment]
> the answer seems to be software-specific in many cases, so I wonder about our ability to provide guidance which is both sufficiently general to encompass

Yes for sure, but something general like the following example would be more helpful than what mildly technical users (who don't fully understand some of the lower level Qubes stuff) like myself have to work with. 

`"If installing from a git repo that installs dependencies from various package mangers and other sources: do Step X, then Step Y, then Step Z"`


>  the closest thing to a generally-applicable procedure is simply to use a StandaloneVM

Yes @rootkovska did a mild explainer on this a few months ago in re: to how I best setup my webdev environment (which downloads lots of random JS and Ruby gems), a StandaloneVM was the right answer. But, that seems a bit unrealistic performance / space wise for individuals apps that user wants to isolate, e.g. a Bitcoin wallet.

**Comment by rootkovska** [comment]
I agree with need a more user-friendly way to install apps (both from repos and individual .rpm or .tgz). I think there are two somehow different problems:

1. Where to install things (this is about resolving the resources/security tradeoffs): standalone VM, template for the currently used AppVM, home dir in the current AppVM,

2. The UX workflow required: e.g. finding the right template VM, starting it, stopping, restarting the AppVM, or: realizing we're in a standalone VM and can proceed with the installation immediately.

While the #1 requires (currently) a conscious decision from the user, the #2 should be automated once the user (or an administrator) made a choice in the step #1.

**Comment by v6ak** [comment]
I would add https://github.com/QubesOS/qubes-issues/issues/1455 , because interacting with other than current window looks very weird and reason might look unclear.

**Comment by kingneutron** [comment]
Please, forgive me if this has been mentioned elsewhere, but (speaking as an end-user) it's kind of important to have a GUI way of attaching an ISO image to a Qube rather than resorting to the command line. Just wanted to make sure this is referenced in a support ticket.  TIA

Ref: https://www.qubes-os.org/doc/hvm/

**Comment by hexagonrecursion** [comment]
I nominate:

- [ ] switching between multiple keyboard layouts https://github.com/QubesOS/qubes-issues/issues/4294 https://github.com/QubesOS/qubes-issues/issues/3578 https://github.com/QubesOS/qubes-issues/issues/1396

### Rational
In all other operating systems there is a reasonably straightforward way to configure your layout preferences and then switch between layouts with a keyboard shortcut or (for people who don't like keyboard shortcuts) with at most two mouse clicks. QubesOS in its place has a landmine and a huge pain.

### The Landmine
Qubes OS actually does include a mechanism that visually resembles the above mentioned graphical configuration menu. Unfortunately it doesn't work. To be more precise: it sets the keyboard layout for dom0, but not any of DomU. This landmine is [documented](https://www.qubes-os.org/faq/#my-keyboard-layout-settings-are-not-behaving-correctly-what-should-i-do) but that doesn't make it any less of a landmine: the user will hit it first and then maybe find the documentation.

### The Pain
The only working method of switching keyboard layout that is at least somewhat discoverable is:
1. Start the Qubes Manager
2. Select the qube you are working with
3. Click "Set keyboard layout per qube"
4. Select the layout you want from the list of every possible keyboard layout ever. There is currently no graphical way to limit this menu to only the layouts you actually want nor do the previously used layouts get sorted first and the search function (Ctrl+F) is a lie (the search input box appears but only in order to taunt the user some more).
5. Click OK

This method takes much longer than a keyboard shortcut and, more importantly, **is different from the user expectations set up by other operating systems**.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

**In addition,** this issue violates our guideline that [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing). Issues that are about many different things tend to be too messy and chaotic to be helpful for developers. Contrary to their intention, then often lead to nothing being done rather than many things being done. They impose an unnecessary cognitive burden on developers to figure out what is going on and what exactly needs to be done. We should strive to make this part simple and easy for the developers so that they can focus on what they do best.

If anyone believes that this issue should be reopened, please let us know in a comment here.
