### ISSUE TITLE
Rethink website information architecture

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1833]
While working on improvements to the "Downloads" page updates, I realized something- it was starting to become similar to what the [getting started](https://www.qubes-os.org/getting-started/) and [installation guide](https://www.qubes-os.org/doc/installation-guide/) pages are supposed to be. In fact, there are multiple pages relating to "installing Qubes" which link to one another and are a part of this **user story** of **getting Qubes installed on your computer**

- [Getting Started](https://www.qubes-os.org/getting-started/)
- [Installation Guide](https://www.qubes-os.org/doc/installation-guide/)
- [Downloads](https://www.qubes-os.org/downloads/)
- [Verifying Signatures](https://www.qubes-os.org/doc/verifying-signatures/)
- [Install Security](https://www.qubes-os.org/doc/install-security/)

The current organization of these pages has little information architecture and cohesive "flow" to them. Also, due to Qubes' special hardware / security requirements, our partnership with Purism, and goal of having certified partnerships with others, the following pages need to be taken into account:

- [System Requirements](https://qubes-os.org/doc/system-requirements/)
- [Hardware Compatibility](https://www.qubes-os.org/hcl/)
- [Certified Laptops](https://www.qubes-os.org/doc/certified-laptops/)

We want these pages to be as straight forward and aimed at a "User Persona" as possible, as Qubes aims to be usable to a range of user skill levels. The three main personas I see for Qubes are:

1. **Non-technical Users** --> purchase Pursim (or other preferred) laptop with Qubes preinstalled
2. **Mildly-technical Users** --> capable of downloading & verifying ISOs, making bootable USB image
3. **Technical Users** --> interested in learning and examining every little details

I will spend a bit of time in coming week thinking about this and will add comments with proposed solutions to this!

**Comment by axon-qubes** [comment]
I agree these pages can be improved, but we need to focus on *actual user behavior*, not just what users *think* they will want (or, worse yet, what *we* imagine they would want).

We also need to make sure we're being realistic about Qubes' userbase and target audience. Qubes currently requires a high amount of technical aptitude and willingness to learn compared to all mainstream OSes (and even compared to most Linux distros). Rewriting the website and docs to target non-technical people will not, by itself, magically change this. Instead, it will just mean that our website and docs fail to track our *actual* userbase, to their detriment and ours.

So, here are (some of) the questions we need to answer:

1. Who are our users *currently*? (actual userbase)

   Hypothesis: Mainly security-oriented power users and programmers.

2. Who do we *want* our users to be? (target audience)

   Power users? Freedom fighters? Corporations? Everyone? @rootkovska and/or @marmarek should be the one(s) to answer this question.

3. What kind of website/documentation will be most useful to our *actual userbase*?

   We need the answer to question 1 and empirical data on that group of users.

4. What kind of website/documentation will be most useful to our *target audience*?

   We need the answer to question 2 and empirical data on that group of users.

**Comment by mfc** [comment]
I also agree these pages can be improved, acknowledging that they are a lot better than they used to be!

However I disagree with your conclusions @axon-qubes. This is about improving the flow for users, especially less technical ones. See how Tails has redone their installation flow documentation: https://tails.boum.org/install/

Our priority for documentation and website should always be for less technical users, because power users can skip steps and self-direct themselves as appropriate. 

I do think there are more personas/frames for Qubes users than just on a less-more technical spectrum, such as users more interested in Qubes for identity management versus being interested in Qubes for malware protection. But I feel these can be incorporated into user stories/flows as the user goes towards installing.

**Comment by adrelanos** [comment]
Michael Carbone:
> See how Tails has redone their installation flow documentation: https://tails.boum.org/install/

I think the tails web install wizard "looks good at first, but use it,
it really is cumbersome". Why? See:
https://forums.whonix.org/t/tails-installation-assistant-what-do-you-think-about-it/2046/4?u=patrick

**Comment by axon-qubes** [comment]
@mfc: Not sure I understand which part(s) you disagree with. Would you mind stating explicitly what you disagree with, so that we're all on the same page?

**Comment by bnvk** [comment]
As @axon-qubes mentions, the *actual userbase* of Qubes vs. *target audience* is two forces which might (or might not) be opposing, yet *both* must be taken into account. 

IMHO, the target audience (future users) is slightly more important- as that helps *grow* Qubes user base, which is good. Of course, alienating and making it impossible for existing users to find things is bad. I've renamed this to encompass **the whole site** as that is needed to please both.

The main heading of the site should reflect **primary sections** with **sub-sections** we currently have 7 primary sections. Let's try to shrink that to 4 / 5, which takes into account #1841

---

### Tour / About

This section explains to people *"why they should use this completely new approach to a desktop OS."*. This content needs to be easy to understand, firstly to non-technical users; secondly to technical users.

- [ ] Who Should Use Qubes
  - Journalists
  - Activists
  - Human Rights Workers
  - Hackers
  - Software Developers
  - Sys Admins
  - Security Researchers
- [ ] How Does Qubes Work (re: #1774)
  - [What is a Qube](https://raw.githubusercontent.com/bnvk/Designs/master/QubesOS/website/PNGs/what-is-a-qube.png)
  - Types of Qubes
  - [Recipes](https://raw.githubusercontent.com/bnvk/Designs/master/QubesOS/website/PNGs/recipes.png)
- Screenshots
  - [ ] add headings & create list
- Tutorial Video
  - [ ] Consider notes in #1878
- Research
  - Expanded stuff on homepage of site & links to research

### Get Started

This section on-boards users to Qubes. As with the **Tour**. The [Tails instructions](https://tails.boum.org/install/) are an interesting, but I kinda agree with @adrelanos on cumbersomeness in some respects. I like our approach of working with Purism and certified laptops :smile: However, not everyone is willing / able to buy a new computer.

- Buy Qubes Pre-installed (Purism #1902 / others #1771)
- Self Install
  1. Certified Hardware #1904 
  2. Check Your Hardware ([HCL](https://www.qubes-os.org/hcl/))
  3. Download ISO
  4. Verify ISO
  5. Create bootable USB key
- Downloads
- Video Tutorial
  - Links to documentation on corresponding chapters
- Basic Concepts
- *Qubes Official Support (TBD)*

### Docs / Support

Merging the **Help** page (mentioned #1841) with **Docs** makes sense. The items (StackExchange, IRC) don't warrant their own page, as they are just links / little widgets.

- Documentation
- Troubleshooting
- FAQ
- Mailing Lists

*These could go on the sidebar of each page*

- StackExchange
- IRC
- *Qubes Official Support (TBD)*

I prefer **Support** as it semantic encompasses other things better than **Docs** but, if having the former is not intuitive for our existing users, my semantic pedantry can take the back seat.

### Participate / Get Involved / Or...?

- Funding
  - Transparency #1701
  - Partners
  - Donate
- Developing
- Mailing lists
- Contact Us
  - Email, PGP keys
  - IRC

### News / Team / About

I can't think of a good word to encompass these sections. Maybe, I just keep it as **News** and put **Team** as a subpage of that? 

- Media & Press
- Awards & Grants


### Search

- [ ] Move search box (currently in footer) to the top bar #1841

### Store *(Future)*

In the future, it seems we will need a page to encompass all the things people can order from Qubes!

- Purism laptops #1902
- Other Qubes certified laptops #1771
- USB keys with Qubes flashed
- T-shirts, hoodies, stickers #1879
- *Qubes Official Support (TBD)*

Did I miss anything? @mfc @marmarek

**Comment by axon-qubes** [comment]
Instead of combining unrelated pages (e.g., News / Info / About / Team), what about having submenus?

**Comment by marmarek** [comment]
### Tour / About

"About" will be better

### Docs / Support

I think it's really important to have documentation accessible directly from main menu, not only through intermediate "help" page. If you really want just one top menu entry for it, merge those pages, so "help" will be just above documentation index. But do not drop direct link to (maybe modified) documentation index. That top menu entry may be named "Help" if you like it more than "Docs".

### News / Info / About / Team

I would put "Team" into previous category "Participate / Get Involved / Or...?" (FWIW I vote for "Get Involved"), into "Contact Us" part. Then just have "News".

**Comment by unman** [comment]
It now seems difficult to find the information on mailing lists, and really hard to find out how to submit a bug. Surely this wasn't what was envisaged?

**Comment by andrewdavidwong** [comment]
@unman: I'm certainly open to enhancing those aspects of the site.

> It now seems difficult to find the information on mailing lists

Currently, there are two ways to discover the mailing lists:

1. A big icon on the front page in the "Join the Community!" section.
2. A link in "The Basics" section of the Docs page.

I'll add another link to the footer under Team right now.

> and really hard to find out how to submit a bug.

Currently, the way to discover how to report a bug is to see the link to the "Reporting Bugs" page on the Docs page (or to simply send your bug report to one of the mailing lists). I'll add another link to the footer under Team right now. (This doesn't really fit here, but all the other categories seem to fit even worse, and we already have some ill-fitting links here.) I'm not sure it would be a good idea to include a bug report link on the front page.

If you have other suggestions, please share them.

**Comment by andrewdavidwong** [comment]
Also added links to reporting security issues and bugs under the User's Basics section, so they'll be easier to spot from the top of the page.

**Comment by andrewdavidwong** [comment]
Also added links to reporting security issue and bugs to the top of the Team page.

I think that should be enough to make that information easily discoverable now. What do you think, @unman?
