### ISSUE TITLE
meta-ticket: tracking progress/strategy for running Martus in Qubes

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1836]
The secure human rights information collection tool [Martus](https://martus.org/) requires `openjdk 1.8` and the `javafx` package (packaged for Debian as `openjfx`). 

Currently Fedora 23 comes with `openjdk` version `1.8.0_72` but running Martus `java -jar martus.jar` fails because it doesn't have the `javafx`, which is unclear to me how to install.

Currently Debian 8 comes with `openjdk` version `1.7.0_95` which is insufficient to run Martus.

Current potential solutions I see are: 
- [x] ~~change Debian 8 template to unstable or testing and install newer version of `openjdk`~~
- [x] ~~figure out where `javafx` lives in dnf / rpm land and install it in a Fedora 23 template~~
- [x] **install `openjfx` and `openjdk-8-jre` via Debian backports** -- SUCCESS
- [X] install Oracle's proprietary java implementation in a new Debian template -- **would like to avoid**
- [X] run Martus' Windows version within a Windows 7 qube (requires a Windows 7 license and installing W7 within Qubes) -- **would like to avoid**

These issues were first reported and discussed with Martus developers at the [Internet Freedom Festival](https://internetfreedomfestival.org).

**Comment by adrelanos** [comment]
Can you ask the Martus developers please to get their application into the official Debian repositories? That would make integration so much easier!

There is also [Debian Anonymity Tools Team](https://tracker.debian.org/teams/anonymity-tools/) (and perhaps other Debian Developers) that might be interested and willing to help. They could try to get in touch with them.

**Comment by mfc** [comment]
Yes, this has been highlighted to them. Also them packaging it and serving it from their own repo as an intermediary step. They may need help with that process so that's useful link for them.

**Comment by mfc** [comment]
> successfully change Debian 8 template to unstable and install newer version of openjdk

this fails because Debian 8 testing version of openjdk-8-jre also does not come with `javafx`. To create a Debian 8 testing template:

1. create a Debian testing template `qvm-clone debian-8 debian-8-testing`

2. actually change the sources for the new template by opening a terminal in new template, run `sudo vi /etc/apt/sources.list` and add:
```
# add testing & security updates repos
deb http://http.debian.net/debian testing main
deb http://security.debian.org/ testing/updates main
```

3. update source list: `sudo apt-get update`

4. install openjdk from testing: `sudo apt-get install openjdk-8-jre/testing`

5. create new qube/appvm based on your debian-8-testing template with whatever networking and color you want

6. download the latest Martus version from https://martus.org

7. unzip the Martus package `unzip Martus-5.1.1.zip`

8. cd into new folder `cd Martus-5.1.1`

9. run Martus: `java -jar martus.jar`

get same error: `Caused by: java.lang.ClassNotFoundException: javafx.fxml.Initializable`

for reference Debian-8-testing has `openjdk 1.8.0_77-Debian`

**Comment by mfc** [comment]
>  figure out where `javafx` lives in dnf / rpm land and install it in a Fedora 23 template

javafx is not build for Fedora yet: https://bugzilla.redhat.com/show_bug.cgi?id=1145303

**Comment by mfc** [comment]
>  install `openjfx` and `openjdk-8-jre` via Debian backports

!! Works !!

1. create a Debian 8 martus template `qvm-clone debian-8 debian-8-martus`

2. add backports to the sources for the new template by opening a terminal in new template, run `sudo vi /etc/apt/sources.list` and add: `deb http://http.debian.net/debian jessie-backports main`

3. update source list: `sudo apt-get update`

4. install `openjdk` and `openjfx` from backports: `sudo apt-get -t jessie-backports install openjdk-8-jre openjfx`

5. You may need to install `unzip` to be able to unzip Martus after you download it: `sudo apt-get install unzip`

5. create new qube/appvm based on your debian-8-martus template with whatever color and networking you want (`sys-whonix` probably preferred)

6. download the latest Martus version from https://martus.org

7. unzip the Martus package `unzip Martus-5.1.1.zip`

8. cd into new folder `cd Martus-5.1.1`

9. run Martus: `java -jar martus.jar`

**Comment by mfc** [comment]
let's get the instructions into a doc

**Comment by marmarek** [comment]
Looks like a perfect case for VM managing using Salt: https://github.com/QubesOS/qubes-issues/issues/1541
Lets not get better be an enemy of good and still include above steps in documentation. But I'll use this as an example configuration and will report back when finished.

**Comment by axon-qubes** [comment]
Doc page created. Please edit as appropriate.

**Comment by mfc** [comment]
Looks perfect, thanks axon. you can add it to the website docs.

@marmarek sounds good! maybe we can close this ticket and when you are creating examples for salt configuration we can put it there?

**Comment by marmarek** [comment]
Yes, that's ok.
