### ISSUE TITLE
Improving inter-VM file copy / move UX master ticket

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1839]
As per collaborating with a new contributor @kmoragas (and to keep these all in focus) i'm opening this master ticket to track the various `inter-vm file copying / moving` bugs and ideas for UX improvements!
- [x] Consider an option to ask for RPC target VM in dom0 #910
- [x] support copying (multiple) folders also by Qubes gui and qvm-copy-to-vm #1429
- [x] Provide an easy command line tool for copying between vm and dom0 #1324
- [ ] Make file copying errors (in GUI) less technical & cryptic #1240 
- [x] File copy/move error not given window focus #1802
- [x] Let user specify other destination folders for file copying #1793
- [ ] qvm-copy-to-vm incorrect progress report #1519
- [ ] qvm-copy-to-vm behaviour with existing files #1772

These are notes from #1443 which outlined the current workflow user experience we have

```
1. right-click on file, select Copy/Move To VM
2. source qube1 dialog box: user types in destination qubes2 name
3. AdminVM dialog box: confirm file transfer
```

And the proposed simplified workflow we are aiming for

```
1. right-click on file, select Copy/Move To VM
2. AdminVM dialog box: select destination VM (confirmation of file transfer is implicit)
```

**Comment by mfc** [comment]
we may need core dev help on this since there hasn't been any public movement on this for two months, given the R3.2 milestone and how long we have been postponing this. or else we need to split some of these tasks into essential R3.2 tasks (#910) and nice-to-have R4/R3.3 tasks (everything else).

**Comment by adrelanos** [comment]
Michael Carbone:
> we may need core dev help on this since there hasn't been any public
> movement on this for two months, given the R3.2 milestone and how
> long we have been postponing this.

Yes.

https://github.com/QubesOS/qubes-issues/issues/1700

> or else we need to split some of
> these tasks into essential R3.2 tasks (#910) and nice-to-have R4/R3.3
> tasks (everything else).

I don't think we have a big list of nice-to-have things assigned.
Everyone has different needs and other priorities on its wishlist. So I
don't think that is our issue.

**Comment by andrewdavidwong** [comment]
In https://github.com/QubesOS/qubes-issues/issues/3353#issuecomment-348268229, @ohreally wrote:
> The dialog which appears to confirm the action asks me to confirm operation qubes.Filecopy. This is a bit confusing, since I, as a layman user, would expect qubes.Filemove. Which probably doesn't even exist, but I am now asked to confirm an operation I did not request.
>
> And the same dialog does not have the target VM selected, even when I run qvm-move-to-vm from the command line (which means that I have already specified the target).

I have recently seen many (at least half a dozen) other users make similar remarks about how the new 4.0 inter-VM copy dialogue box VM target specification system is confusing.

CC: @marmarek

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
