### ISSUE TITLE
[dom0 GUI suggestion tracker] dom0 Qubes VM Manager panel: suggestions to improve the list view and GUI improvements

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2547]
#### Qubes OS version (e.g., `R3.2`):
3.2

#### Suggestions
- [ ] add an option to add a column with a "Shutdown VM" or "Shutdown VM immediately" (see below) button [rationale: this is the most-often used function in the panel. I want to save clicks.]
- [ ] add option to add further button columns for Start/Resume VM, Pause VM ... [less important]
- [ ] "Shutdown VM immediately": add option to skip confirmation prompt "VM Shutdown Confirmation" (either global- or per-VM-setting) [rationale: I don't like that 'superfluous' prompt window after already having clicked the VM row, or right-clicked the VM and then clicked "Shutdown VM"). Save clicks!]

**Comment by andrewdavidwong** [comment]
This will soon be deprecated by #2132. Given that we closed #1870 as a "duplicate" for this reason (though not strictly a duplicate), I think we should close this for the same reason. (This issue is more like a duplicate of #1870.)
