### ISSUE TITLE
Full touchscreen support

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#3887]
An umbrella issue what is needed for full touschscreen support.

- [x] https://github.com/QubesOS/qubes-issues/issues/2281 input proxy support
- [ ] Qubes has at least one touch-friendly DE (e.g., https://github.com/QubesOS/qubes-issues/issues/1806 or Android GUIVM)
- [ ] Touches work well with multi-monitor setup when using some touch-friendly DE and input proxy – regardless of screen positions. (It might require no implementation, but it should be verified if it works well. See https://github.com/QubesOS/qubes-issues/issues/2281#issuecomment-386517462 for more details.)
- [ ] Support in guests: https://github.com/QubesOS/qubes-issues/issues/3337
- [ ] Optional: Touchegg or something similar for multitouch gestures.

According to https://laptop.ninja/the-best-linux-distributions-for-touchscreens/ , the best DE for touchscreen are Gnome 3 and Unity. Since Unity is probably dead, Gnome Shell looks reasonable. They suggest using touchegg, I am adding it on the list.

**Comment by bi0shacker001** [comment]
I'd argue KDE is extremely touch-friendly now.
