### ISSUE TITLE
Installer option to automatically rescue existing install from common boot issues

### ISSUE THREAD

**Issue by comods** [QubesOS/qubes-issues#3973]
Installer option to automatically rescue existing install from common boot issues.
This is an industry standard expected by normal users and mandatory for a good user experience (even if Qubes OS is flawless, other things can corrupt the boot sequence).

### Qubes OS version:

Qubes-R4.0-x86_64.iso (I burned to DVD and installed onto a blank computer)

### Affected component(s): 

Entire Qubes OS as it doesn't boot to the screen asking for your encrypted hard drive password.
Qubes-R4.0-x86_64.iso's "Rescue a Qubes system" needs updated with this new feature.

---

### Steps to reproduce the behavior:

Install Qubes OS R4.0.
`sudo qubes-dom0-update` or `sudo qubes-dom0-update --enablerepo=qubes-dom0-security-testing`
> During the step `Install  kernel-qubes-vm-1000:4.14.41-1.pvops.qubes.x86_64` this error displays:
> `cp: error writing '/boot/efi/EFI/qubes/initramfs-4.14.41-1.props.qubes.x86_64.img': no space left on device.`
> Note /boot/efi/EFI/qubes/initramfs-4.14.41-1.props.qubes.x86_64.img may exist, taking up the rest of the free space, but is only a corrupted part of the intended file.

Reboot your computer.
```
[...] initramfs unpacking failed: read error 
[...] Unable to mount root fs, Kernal Panic
[...] ... 
[...] Kernal Offset disabled
[...] Kernal Panic: Not Syncing
```
Burn Qubes-R4.0-x86_64.iso to a DVD & Boot from it.
Select "Troubleshooting", then "Rescue a Qubes system".
The only options are to be dropped into a shell, even though the fix can be automated.
`chroot /mnt/sysimage`
`vim /boot/efi/EFI/qubes/xen.cfg`
Change `default=...` to have the `...` be one of the options listed below in the same file.
Reboot your computer.

### Expected behavior:

1) Qubes OS doesn't boot to the to the screen asking for your encrypted hard drive password.
2) Burn Qubes-R4.0-x86_64.iso to a DVD & Boot from it.
3) Select "Troubleshooting" then "Rescue a Qubes system".
4) The Rescue Environment displays:
```
======================================================
Rescue

The rescue environment will now attempt to find your Linux installation.  Choose '1' to automatically rescue from common issues and downloading files as needed. This will NOT use whonix/tor.  Choose '2' for an offline automatic rescue.  Choose '3' to have your installation mounted under the directory : /mnt/sysimage. You can then manually make any changes required to your system.  Choose '4' to mount as read-only instead of read-write.
If for some reason this process does not work choose '5' to skip directly to a shell.

 1) Automatic (Download as needed)

 2) Automatic (Offline)

 3) Manual

 4) Manual (Read-only mount)

 5) Manual (Skip to shell)

 6) Quit (Reboot)

Please make a selection from the above:  1
======================================================
```
Selecting '1' for automatic, will do the following rescue steps:

Note: Before each rescue step makes its change:
- Verify this step's problem exists, otherwise skip this step.
- Verify they will not run out of disk space while making their change.
- If boot up fix requires more disk space, free up disk space (one way is by deleting an unused kernel) but try to not ask for permission (for safe files to delete) unless you detect an anomaly (like a duel boot needs the kernel files your are deleting).

[Admins, feel free to edit this post to update these checkboxes as needed]
- [ ] If the mounted drive `/boot/efi/` is full, before making a change, free up enough space for that change to not error out.
- [ ] Verify /boot/efi/EFI/qubes/xen.cfg the `default=...` has `...` set to one of the options listed below in the same file and one that passes the following tests. (If listed, use non-corrupt rescue kernel, #3624)
- Note: Include in the Qubes OS Install iso a list of hashes (SHA256?) for all kernel files (That Qubes has ever provided in Installer or dom0 update) and maybe their file sizes too.
- [ ] Try to download updated hashes list (but continue rescue either way).
- [ ] Verify default kernel has all the files needed for it to boot and they match their hashes.
- [ ] If a kernel file doesn't match known hashes, verify there is enough free space (freeing space as needed) and then try to redownload all corrupt files.
- [ ] If no kernel is usable, install and use a rescue kernel stored on the Qubes Installer iso (See #3624) (Free space as needed)

More rescue steps to add:
- [ ] When needed, automatically apply fixes detailed in #3700 (Disable appvms automatically booting).
- [ ] When needed, automatically apply fixes detailed in #3915.
- [ ] With each individual fix when its needed, automatically apply fixes detailed in https://www.qubes-os.org/doc/uefi-troubleshooting/ (Automate as many individual fixes possible)
- [ ] When needed, automatically apply fixes detailed in #3949.
- [ ] When needed, automatically apply fixes detailed in #3903.
- [ ] When needed, automatically apply fixes detailed in #3790.
- [ ] When needed, automatically apply fixes detailed in #3690.
- [ ] When needed, automatically apply fixes detailed in #3619 (Detach usb devices when needed).
- [ ] When needed, automatically apply fixes detailed in #3897 (when fix is found).
- [ ] When needed, automatically apply know fixes to as many types of kernel panics as possible.
- [ ] When needed, automatically apply fixes detailed in #3972. (Detect current UTC time from NTP, check if hwclock is UTC or localtime, & update hwclock as needed)

### Actual behavior:

During `sudo qubes-dom0-update` the step `Install  kernel-qubes-vm-1000:4.14.41-1.pvops.qubes.x86_64` doesn't clean itself up after the error `cp: error writing '/boot/efi/EFI/qubes/initramfs-4.14.41-1.props.qubes.x86_64.img': no space left on device.`
Reboot entire computer.
Qubes OS doesn't boot to the screen asking for your encrypted hard drive password.
Burn Qubes-R4.0-x86_64.iso to a DVD & Boot from it.
Select "Troubleshooting", then "Rescue a Qubes system".
The only options are to be dropped into a shell, even though the fix can be automated.
Google error & ask community support. Community support implies that it is normal for the Qubes OS recovery DVD to not be able to automatically fix or rollback a dom0 update (from following a Qubes Security Bulletin) nor any common boot issue. A common user then hates Qubes OS and installs a different operating system.

**Comment by RefinedSoftwareLLC** [comment]
Per: https://groups.google.com/forum/#!topic/qubes-users/JwLKyzg32ao
- [ ] When needed, automatically remove rd.qubes.hide_all_usb Kernel Param if no PS/2 port is in use to enter hard drive password.

**Comment by RefinedSoftwareLLC** [comment]
Automatic Rescue should save a log of all the changes it made (if it has access to a hard drive with free space?). This allows debugging if something goes wrong, but also for self taught users to see what was needed to fix their system, and power users to manually revert changes as they wish (maybe to fix a duel boot that broke when getting Qubes OS to boot).

**Comment by 4NobleTruths** [comment]
This is a very important issue.
Right now, my team has a Qubes 4 machine down after a dom0 update.
We don't know what to do next.
We were going to try to rescue it with the install USB, but this issue and the response to it, suggests that would be a waste of time to even try, without contacting the few advanced users that can even help, if they have time and motivation...

**Comment by brendanhoar** [comment]
At a minimum, it'd be nice to make it more obvious in grub how to boot the system from an older xen+kernel combination. I got so confused at one point I changed the grub layout to always show all possible combinations.

Of course, since then I only had one bad kernel update, probably due to Qubes rebooting before dracut was done.

**Comment by agrodowski** [comment]
After today's dom0 update, I failed into this pit...

`Initramfs unpacking failed: read error`
`Kernel panic - not syncing: Attempted to kill initf exitcode=0x00007f00`
`CPU: 4 PID: 1 Comm: init Not tainted 4.19.107-1.pvops.qubes.x86_64 #1`
`Hardware name: Dell Inc. XPS 15 7590/0VYV0G, BIOS 1.6.0 02/06/2020`
`...`
`Kernel Offset: disabled`

I had to change the default kernel back to the old one (94) in the boot partition, but what could have gone wrong? I do not recall seeing any errors during the dom0 update...

**Comment by marmarek** [comment]
Most likely out of disk space in /boot.

**Comment by agrodowski** [comment]
Yeah... /boot seems pretty large, but /boot/efi is not, indeed. I will try to resize it, if possible.

`df -m`
Filesystem | 1-M blocks | Used | Available | Use% | Mounted On
---------------|----------------|---------|-------------|----------|-----------------
/dev/nvme0n1p7  | 976 | 72  | 837 |  8% |  /boot
/dev/nvme0n1p1  | 176 | 147 | 30 |  84% | /boot/efi

**Comment by agrodowski** [comment]
Ok, for some strange reasons, I only had ~13M of initramfs-4.19.107 within /boot/efi that normally has ~24M. Luckily, a copy is also made in /boot, so I could copy the full image manually to /boot/efi and it boots properly now, leaving me with only 20M of free space within /boot/efi. So, max 2 kernels.

Does the dom0 update process require an extra ~40M space within /boot/efi for some reason?
