### ISSUE TITLE
Prepare R4.1 -> R4.2 upgrade tool

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7832]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Similar to #5685, we'll need an upgrade tool.

### The solution you'd like

For now this issue is a placeholder to collect tasks the tool will need to do.

- [x] Debian template: ensure proper apt sources.list update: https://github.com/QubesOS/qubes-core-agent-linux/pull/371#issuecomment-1096833133
- [x]  take a dom0 snapshot, in case of power failure.
- [x] set `GRUB_DISABLE_SUBMENU=false` in `/etc/default/grub`
- [x] ensure grub.cfg is in new place (https://github.com/QubesOS/qubes-issues/issues/7985) - theoretically already handled by grub install script
- [x] migrate qrexec policy to the new format (https://github.com/QubesOS/qubes-issues/issues/8000)
- [x] switch default menu (https://github.com/QubesOS/qubes-issues/issues/7939)
- [x] switch to pipewire in relevant templates (all Fedora, Debian >= 12); magic command for Fedora: `dnf swap--allowerasing pulseaudio pipewire-pulseaudio`

**Comment by DemiMarie** [comment]
[ ] take a dom0 snapshot, in case of power failure.
